
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "python"
      POSTGRES_USER: posgtres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - my-network

  app:
    image: fnatikjk/python
    container_name: app
    environment:
      - TEST=123
    ports:
      - 8000:8000
    networks:
      - my-network

  front:
    image: fnatikjk2/python-front
    container_name: front
    depends_on:
      - app
    ports:
      - 3000:3000
    networks:
      - my-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
      - front
    networks:
      - my-network

volumes:
  redis_data:
  postgres_data:

networks:
  my-network:
    driver: bridge