"""empty message

Revision ID: 7e85c25d6107
Revises: 726cc17ccabc
Create Date: 2025-09-17 00:42:25.994117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e85c25d6107'
down_revision: Union[str, Sequence[str], None] = '726cc17ccabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'blockReason',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.create_unique_constraint(None, 'accounts', ['id'])
    op.create_unique_constraint(None, 'notifications', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='unique')
    op.drop_constraint(None, 'accounts', type_='unique')
    op.alter_column('accounts', 'blockReason',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###
